from __future__ import annotations

"""Native SM90 fallback compiler for extracted StageML residual kernels.

This module exists because some IREE CUDA builds currently fail while
constructing target metadata for Hopper targets such as sm_90.  The fallback is
not an IREE replacement.  It is a narrow artifact path that proves StageML can
emit an extracted static residual kernel and compile a native H100 CUDA artifact
when IREE sm_90 lowering is unavailable.
"""

from dataclasses import asdict, dataclass
from pathlib import Path
import json
import shutil
import subprocess
from typing import Any


@dataclass(frozen=True)
class NativeSM90Config:
    output_dir: str
    tokens: int = 16
    hidden: int = 4096
    output: int = 4096
    dtype: str = "f32"
    arch: str = "sm_90"
    nvcc: str = "nvcc"
    module_name: str = "stageml_materialized_residual_sm90"

    @property
    def out_dir(self) -> Path:
        return Path(self.output_dir)

    @property
    def cu_path(self) -> Path:
        return self.out_dir / f"{self.module_name}.cu"

    @property
    def ptx_path(self) -> Path:
        return self.out_dir / f"{self.module_name}.ptx"

    @property
    def cubin_path(self) -> Path:
        return self.out_dir / f"{self.module_name}.cubin"


@dataclass
class NativeSM90Result:
    status: str
    command_ptx: list[str]
    command_cubin: list[str]
    output_dir: str
    cu: str | None
    ptx: str | None
    cubin: str | None
    returncode_ptx: int | None = None
    returncode_cubin: int | None = None
    stdout_ptx: str = ""
    stderr_ptx: str = ""
    stdout_cubin: str = ""
    stderr_cubin: str = ""
    reason: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def emit_native_sm90_cuda(config: NativeSM90Config) -> Path:
    """Emit a simple static residual matmul CUDA kernel.

    The kernel computes C[M,N] = A[M,K] * B[K,N].  It is intentionally simple.
    Its purpose is backend artifact validation, not performance superiority.
    """
    if config.dtype != "f32":
        raise ValueError("native SM90 fallback currently supports dtype=f32 only")
    m = int(config.tokens)
    k = int(config.hidden)
    n = int(config.output)
    code = f"""// Generated by StageML native SM90 fallback.
// Shape: A[{m},{k}] x B[{k},{n}] -> C[{m},{n}]
// This file is a backend artifact check, not an optimized GEMM kernel.
extern \"C\" __global__
void stageml_materialized_residual_sm90(const float* __restrict__ a,
                                        const float* __restrict__ b,
                                        float* __restrict__ c) {{
  const int row = blockIdx.y * blockDim.y + threadIdx.y;
  const int col = blockIdx.x * blockDim.x + threadIdx.x;
  if (row >= {m} || col >= {n}) return;
  float acc = 0.0f;
  for (int kk = 0; kk < {k}; ++kk) {{
    acc += a[row * {k} + kk] * b[kk * {n} + col];
  }}
  c[row * {n} + col] = acc;
}}
"""
    config.out_dir.mkdir(parents=True, exist_ok=True)
    config.cu_path.write_text(code)
    return config.cu_path


def build_nvcc_commands(config: NativeSM90Config) -> tuple[list[str], list[str]]:
    ptx_cmd = [
        config.nvcc,
        "-ptx",
        f"-arch={config.arch}",
        str(config.cu_path),
        "-o",
        str(config.ptx_path),
    ]
    cubin_cmd = [
        config.nvcc,
        "-cubin",
        f"-arch={config.arch}",
        str(config.cu_path),
        "-o",
        str(config.cubin_path),
    ]
    return ptx_cmd, cubin_cmd


def compile_native_sm90(config: NativeSM90Config, *, dry_run: bool = False) -> NativeSM90Result:
    config.out_dir.mkdir(parents=True, exist_ok=True)
    emit_native_sm90_cuda(config)
    ptx_cmd, cubin_cmd = build_nvcc_commands(config)
    if dry_run:
        return NativeSM90Result(
            status="dry_run",
            command_ptx=ptx_cmd,
            command_cubin=cubin_cmd,
            output_dir=str(config.out_dir),
            cu=str(config.cu_path),
            ptx=str(config.ptx_path),
            cubin=str(config.cubin_path),
            reason="dry run requested",
        )
    if shutil.which(config.nvcc) is None:
        return NativeSM90Result(
            status="error",
            command_ptx=ptx_cmd,
            command_cubin=cubin_cmd,
            output_dir=str(config.out_dir),
            cu=str(config.cu_path),
            ptx=None,
            cubin=None,
            reason=f"{config.nvcc} was not found on PATH",
        )
    ptx_proc = subprocess.run(ptx_cmd, text=True, capture_output=True)
    cubin_proc = subprocess.run(cubin_cmd, text=True, capture_output=True)
    ok = ptx_proc.returncode == 0 and cubin_proc.returncode == 0 and config.ptx_path.exists() and config.cubin_path.exists()
    return NativeSM90Result(
        status="ok" if ok else "error",
        command_ptx=ptx_cmd,
        command_cubin=cubin_cmd,
        output_dir=str(config.out_dir),
        cu=str(config.cu_path),
        ptx=str(config.ptx_path) if config.ptx_path.exists() else None,
        cubin=str(config.cubin_path) if config.cubin_path.exists() else None,
        returncode_ptx=ptx_proc.returncode,
        returncode_cubin=cubin_proc.returncode,
        stdout_ptx=ptx_proc.stdout,
        stderr_ptx=ptx_proc.stderr,
        stdout_cubin=cubin_proc.stdout,
        stderr_cubin=cubin_proc.stderr,
        reason="" if ok else "native sm_90 CUDA compilation failed",
    )


def write_native_sm90_result(path: str | Path, result: NativeSM90Result) -> Path:
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(result.to_dict(), indent=2, sort_keys=True) + "\n")
    return out
