from __future__ import annotations

"""Triton code generation utilities for accepted StageML residual plans.

The generator emits a runnable Python module containing a Triton matmul kernel
for the already-materialized residual weight.  For large models the generated
code keeps the fused weight in a sidecar ``.pt`` file and passes a pointer to the
kernel.  That still removes the dynamic LoRA pointer chasing from the hot path:
the kernel sees only ``x`` and ``w_residual``.

Inlining billions of weight constants directly into source code is not practical,
so the generator only supports literal inlining for very small tensors.  The
paper-facing claim should therefore be "generated Triton kernel for the
materialized residual weight", not "entire Mixtral weights printed as Python
constants".
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import torch

from stageml.moe_ir import ExpertPlan, PlanKind, ResidualPlan


@dataclass(frozen=True)
class TritonKernelConfig:
    name: str = "stageml_residual_matmul"
    block_m: int = 16
    block_n: int = 16
    block_k: int = 32
    num_warps: int = 4
    num_stages: int = 4
    inline_weight_numel_limit: int = 4096


def _sanitize_symbol(text: str) -> str:
    chars = []
    for ch in str(text):
        chars.append(ch if (ch.isalnum() or ch == "_") else "_")
    out = "".join(chars).strip("_")
    if not out:
        out = "stageml_kernel"
    if out[0].isdigit():
        out = "_" + out
    return out


def generate_residual_matmul_source(
    *,
    module_name: str = "stageml_generated_residual_kernel",
    kernel_name: str = "stageml_residual_matmul_kernel",
    wrapper_name: str = "residual_matmul",
    config: TritonKernelConfig | None = None,
) -> str:
    """Return Python source for a Triton residual matmul module.

    The generated wrapper computes ``x @ w_residual.T``.  Shapes are dynamic at
    runtime, while tile sizes are compile-time constants.
    """
    config = config or TritonKernelConfig()
    kernel_name = _sanitize_symbol(kernel_name)
    wrapper_name = _sanitize_symbol(wrapper_name)
    return f'''# Auto-generated by stageml.triton_generator. Do not edit by hand.
from __future__ import annotations

import torch
import triton
import triton.language as tl


@triton.jit
def {kernel_name}(
    X,
    W,
    Y,
    M: tl.constexpr,
    N: tl.constexpr,
    K: tl.constexpr,
    stride_xm: tl.constexpr,
    stride_xk: tl.constexpr,
    stride_wn: tl.constexpr,
    stride_wk: tl.constexpr,
    stride_ym: tl.constexpr,
    stride_yn: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    BLOCK_K: tl.constexpr,
):
    pid_m = tl.program_id(0)
    pid_n = tl.program_id(1)

    offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    offs_n = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)
    offs_k = tl.arange(0, BLOCK_K)

    acc = tl.zeros((BLOCK_M, BLOCK_N), tl.float32)
    for k0 in range(0, K, BLOCK_K):
        k_idxs = k0 + offs_k
        x_ptrs = X + offs_m[:, None] * stride_xm + k_idxs[None, :] * stride_xk
        w_ptrs = W + offs_n[None, :] * stride_wn + k_idxs[:, None] * stride_wk
        x = tl.load(x_ptrs, mask=(offs_m[:, None] < M) & (k_idxs[None, :] < K), other=0.0)
        w = tl.load(w_ptrs, mask=(offs_n[None, :] < N) & (k_idxs[:, None] < K), other=0.0)
        acc += tl.dot(x, w)

    y_ptrs = Y + offs_m[:, None] * stride_ym + offs_n[None, :] * stride_yn
    tl.store(y_ptrs, acc, mask=(offs_m[:, None] < M) & (offs_n[None, :] < N))


def {wrapper_name}(x: torch.Tensor, w_residual: torch.Tensor) -> torch.Tensor:
    """Compute x @ w_residual.T using the generated Triton kernel.

    x shape:          [M, K]
    w_residual shape: [N, K]
    output shape:     [M, N]
    """
    if x.ndim != 2 or w_residual.ndim != 2:
        raise ValueError("x and w_residual must be rank-2 tensors")
    if x.shape[1] != w_residual.shape[1]:
        raise ValueError(f"shape mismatch: x={{tuple(x.shape)}} w={{tuple(w_residual.shape)}}")
    if not x.is_cuda or not w_residual.is_cuda:
        raise ValueError("generated Triton residual kernel requires CUDA tensors")

    x = x.contiguous()
    w_residual = w_residual.contiguous()
    M, K = x.shape
    N = w_residual.shape[0]
    y = torch.empty((M, N), device=x.device, dtype=x.dtype)
    grid = (triton.cdiv(M, {int(config.block_m)}), triton.cdiv(N, {int(config.block_n)}))
    {kernel_name}[grid](
        x,
        w_residual,
        y,
        M,
        N,
        K,
        x.stride(0),
        x.stride(1),
        w_residual.stride(0),
        w_residual.stride(1),
        y.stride(0),
        y.stride(1),
        BLOCK_M={int(config.block_m)},
        BLOCK_N={int(config.block_n)},
        BLOCK_K={int(config.block_k)},
        num_warps={int(config.num_warps)},
        num_stages={int(config.num_stages)},
    )
    return y
'''


def write_residual_matmul_kernel(
    path: str | Path,
    *,
    kernel_name: str = "stageml_residual_matmul_kernel",
    wrapper_name: str = "residual_matmul",
    config: TritonKernelConfig | None = None,
) -> Path:
    """Write a generated Triton residual matmul module."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        generate_residual_matmul_source(
            kernel_name=kernel_name,
            wrapper_name=wrapper_name,
            config=config,
        ),
        encoding="utf-8",
    )
    return p


def materialize_residual_weight(
    base_weight: torch.Tensor,
    a: torch.Tensor,
    b: torch.Tensor,
    *,
    scaling: float = 1.0,
) -> torch.Tensor:
    """Return W + scaling * B @ A in StageML's [out, in] layout."""
    if base_weight.ndim != 2:
        raise ValueError("base_weight must have shape [out_features, in_features]")
    if a.ndim != 2 or b.ndim != 2:
        raise ValueError("a and b must be rank-2 LoRA factors")
    if a.shape[1] != base_weight.shape[1]:
        raise ValueError("A must have shape [rank, in_features]")
    if b.shape[0] != base_weight.shape[0] or b.shape[1] != a.shape[0]:
        raise ValueError("B must have shape [out_features, rank]")
    return (base_weight + float(scaling) * (b @ a)).contiguous()


def write_kernel_package(
    out_dir: str | Path,
    *,
    base_weight: torch.Tensor | None = None,
    a: torch.Tensor | None = None,
    b: torch.Tensor | None = None,
    scaling: float = 1.0,
    config: TritonKernelConfig | None = None,
) -> dict[str, str]:
    """Write a runnable Triton kernel package.

    If weights are supplied, the materialized residual tensor is saved to
    ``w_residual.pt``.  The generated code remains generic and receives the
    weight as a pointer at runtime.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    kernel_path = write_residual_matmul_kernel(out / "generated_residual_kernel.py", config=config)
    result = {"kernel_py": str(kernel_path)}
    if base_weight is not None and a is not None and b is not None:
        w_residual = materialize_residual_weight(base_weight, a, b, scaling=scaling).detach().cpu()
        weight_path = out / "w_residual.pt"
        torch.save(w_residual, weight_path)
        result["w_residual_pt"] = str(weight_path)
    return result


def generate_kernel_from_residual_plan(
    plan: ResidualPlan,
    out_dir: str | Path,
    *,
    config: TritonKernelConfig | None = None,
) -> dict[str, str]:
    """Generate a Triton module for every materialized residual plan entry.

    This function emits code for the accepted residual plan structure.  It does
    not need the large model tensors; tensor values are supplied at runtime or by
    ``write_kernel_package``.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written: dict[str, str] = {}
    for idx, p in enumerate(plan.plans):
        if p.kind != PlanKind.MATERIALIZED_RESIDUAL:
            continue
        name = _sanitize_symbol(f"{p.adapter}_{p.expert}_{idx}")
        kernel_path = write_residual_matmul_kernel(
            out / f"generated_residual_{name}.py",
            kernel_name=f"stageml_residual_matmul_{name}",
            wrapper_name="residual_matmul",
            config=config,
        )
        written[name] = str(kernel_path)
    return written
